### ISSUE TITLE
Docker Software Compilation Issue

### ISSUE THREAD

**Issue by zin-lin** [adaptive-intelligent-robotics/Qutee_v2#1]
Dear Developers, we are a group of students from Edinburgh Napier University researching on the Qutee robot. We would like to know how to compile the right way. We have followed the instructions on the software Readme.md. Pulling those docker images worked perfectly well, but when compiling from idf.py build inside the docker, it won't build the project. It has a couple of potential version problems for the CMakeList. Even changing the version still doesn't work with certain libraries like arduino missing. For your information we have also pull all the submodules and still doesn't work. The problems we encounters are esp32s3 component missing, arduino component missing. The Esp IDF, says we don't need those libraries but we don't know if we need esp_ipc and esp_hid components that are missing. Please guide us on how to build this with idf.py build inside the docker and how the entry point is accessed the right way. If this is the issue that is needed to be solved we are willing to help with what we can.

**Comment by Aneoshun** [comment]
Hi,
I will do my best to help. I found that the overall ESP IDF configuration quite troublesome to set up properly, but that was the only way I found to get a proper compilation environment. (note: using arduino-IDF is not possible as we need to change the registry config in the ESP32 to enable half-duplex uart for the dynamixels). 

I am pretty sure that you need the esp32s3 component. Otherwise, the IDF won't know the characteristics of the board. 
You can change the board target, and hopefully trigger an install of the library, by pressing the button at the bottom of the IDF which says "ESP32S3" in the following screenshot. 
![Screenshot 2024-02-13 at 16 26 00](https://github.com/adaptive-intelligent-robotics/Qutee_v2/assets/6448924/b595d649-4ddc-4017-9788-e5441d9a4ef1)


It will help me if you can list step by step what you did, and what are the error messages on your end. I will try to reproduce this on my side and guide you.

**Comment by zin-lin** [comment]
Firstly, we follow through with 
```shell
docker run -it --rm --user espidf --volume="/etc/timezone:/etc/timezone:ro" -v $(pwd):/micro_ros_espidf_component -v /dev:/dev --privileged --workdir /micro_ros_espidf_component microros/esp-idf-microros:foxy /bin/bash
```
command in my shell. Then we ran idf.py build. Are we missing some steps? We also pulled all the submodules
![image](https://github.com/adaptive-intelligent-robotics/Qutee_v2/assets/68193178/f3228ca3-22d5-4933-831c-467edee9160c)
This is the problem we are encountering, so I have to change it to esp32 which is included in the components. but not esp32s3. This is our first error, I will update you with the next step after we know how to solve this. Thanks again

**Comment by Aneoshun** [comment]
Did you try to do "idf.py menuconfig" first? If yes, how did it go and were you able to change the target?

**Comment by zin-lin** [comment]
Thanks, I will get back to you, I think I need to install the esp32s3 locally as the target, I will do that now. Thanks again

**Comment by zin-lin** [comment]
Dear @Aneoshun, do we need to plug ESP32s3 in to test the code? I cannot get the component, and when I open the project on VSCode I cannot set the target, I might not have set up the project right. Or is there a way to install the esp32s3 in the docker from the terminal. I will first look into what I should do with it and I will get back to you tomorrow and update my situation. Again thank you very much for the help.

**Comment by Aneoshun** [comment]
No, you don't need the hardware module to compile the code. You only need the module when you want to flash it, which happens in a separate stage after the compilation.

**Comment by zin-lin** [comment]
I see. As I have not work with Cpp for such project, usually I use python I might be missing some set up features for the project. Is the editor you have used VSCode or VS22. I would like to know how to set up the project with the board target. I have tried and failed. Can you kindly guide us through that. Thanks. And also I found that the package has been refactored by ESPIDF OG devs 
![image](https://github.com/adaptive-intelligent-robotics/Qutee_v2/assets/68193178/6b706dda-36a0-48cd-841d-a4ee6e208918)
So in theory when we pull foxy it should all work out. If not I can manually download and use the esp32s3 lib for c/cpp on github

quick thing to update, I have manually through shell scripts install esp-idf locally on my Ubuntu. it seems that there, the target which is esp32s3 can be installed. I think it has something to do with micro_espidf_components, as 
```shell
./install.sh esp32s3 
```
doesn't work. It will say stuff like requirement already satisfied, while showing older libs like esp32s2 but never tried to install s3 version

**Comment by Aneoshun** [comment]
Hi, 
I decided to re-work the entire build process to make it simpler. Now everything can be done via terminal (you don't need vscode, or any IDE). 
I also created a custom docker container to use directly the right esp-idf version. 

Could you please follow the new instructions and let me know if you have any issue:  https://github.com/adaptive-intelligent-robotics/Qutee_v2/tree/main/software

Thanks.

**Comment by zin-lin** [comment]
Thanks again for the response. I still have an error 
```shell
In file included from /micro_ros_espidf_component/main/Qutee.cpp:1:
/micro_ros_espidf_component/main/Qutee.hpp:15:10: fatal error: arduino.h: No such file or directory
   15 | #include "arduino.h"
      |          ^~~~~~~~~~~
compilation terminated.


```

But esp32s3 can be done now. I don't know where this error comes from. I can build it for target esp32s3 outside the docker when installing the esp-idf platform onto my ubuntu terminal. but still the same problem.
I believe I can't flash the firmware siince no Qutee.bin is formed but I can menuconfig. It might be a micro_ros_espidf_ccomponent problem.

**Comment by zin-lin** [comment]
Ok I have found the issue. In your code in the main/Qutee.hpp while using Arduino feature the import written was
```c++
#include "arduino.h" 
// original version

#include "Arduino.h"
 // corrected
``` 
once we do this then we can build and Qutee.bin is there. With this I would like to thank you again for your time. and I will go ahead and close this.
